Removed BOP Cherry Compat
BOP doesn't have cherry trees anymore size Minecraft 1.20 introduced Cherry trees.

Fixes error message: "Parsing error loading recipe create:cutting/compat/biomesoplenty/stripped_cherry_log
com.google.gson.JsonSyntaxException: Unknown item 'biomesoplenty:stripped_cherry_log'"